import type { Metadata } from "next";
import { Comfortaa, Comic_Neue, Pacifico, Baloo_2 } from "next/font/google";
import "./globals.css";
import LandingNavbar from "@/components/landingPage/LandingNavbar";

import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});
const baloo = Baloo_2({
  weight: ["500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-baloo",
});

const comic_neue = Comic_Neue({
  variable: "--font-comic-neue",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <SessionProvider session={session}>
        <body
          className={`${comfortaa.variable} ${comic_neue.variable} ${baloo.variable} antialiased`}
        >
          <Toaster />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
